### ISSUE TITLE
Невозможно вставить ссылку на файл с параметрами

### ISSUE THREAD

**Issue by JamesJGoodwin** [nosyash/backrow#1]
При попытке вставить [ссылку с параметром](http://globalv.p.naverrmc.edgesuite.net/c/read/v2/VOD_ALPHA/global_v_2019_10_06_231/449c2901-e83b-11e9-ac0d-246e963a49b9.mp4?__gda__=1570646028_0cfd57de648f441ade570fd4f4b24db0) вылазит ошибка:

> Unsupported video format. Support only .mp4, .m3u8, .webm

Проблема в том, как `filepath.Ext` парсит урлы. Например, вот этот код:

```
filepath.Ext("http://globalv.p.naverrmc.edgesuite.net/c/read/v2/VOD_ALPHA/global_v_2019_10_06_231/449c2901-e83b-11e9-ac0d-246e963a49b9.mp4?__gda__=1570646028_0cfd57de648f441ade570fd4f4b24db0")
```

вернёт не `.mp4`, а `.mp4?__gda__=1570646028_0cfd57de648f441ade570fd4f4b24db0`. Возможно, стоит разбивать строку на подстроки и отделять расширение файла и параметры.

**Comment by nosyash** [comment]
fix
